use_frameworks!

platform :ios, '9.0'

target 'SGUIImageExtension_Example' do
  pod 'SGUIImageExtension', :path => '../'

  target 'SGUIImageExtension_Tests' do
    inherit! :search_paths

    
  end
end
